mosip.kernel.keymanager.url=https://dev.mosip.net
mosip.api.internal.url=https://dev.mosip.net
keycloak.external.url=https://dev.mosip.net
mosip.pms.client.secret=

## For PMS
javax.persistence.jdbc.driver=org.postgresql.Driver
javax.persistence.jdbc.url = jdbc:postgresql://dev.mosip.net/mosip_pms
javax.persistence.jdbc.password =
javax.persistence.jdbc.user = postgres
javax.persistence.jdbc.schema = pms

# Hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.jdbc.lob.non_contextual_creation=true
hibernate.hbm2ddl.auto=none
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.connection.charSet=utf8

spring.datasource.initialization-mode=never

# Keycloak configuration
mosip.iam.base-url=${keycloak.external.url}

#Auth Adapter
mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter
mosip.auth.filter_disable=false
mosip.kernel.auth.adapter.ssl-bypass=true
mosip.kernel.auth.appids.realm.map={prereg:'preregistration',ida:'mosip',registrationclient:'mosip',regproc:'mosip',partner:'mosip',resident:'mosip',admin:'mosip',crereq:'mosip',creser:'mosip',datsha:'mosip'}
auth.server.admin.issuer.uri=${mosip.iam.base-url}/auth/realms/
auth.server.admin.issuer.internal.uri=${mosip.iam.base-url}/auth/realms/

# logging level
logging.level.org.springframework=ERROR
logging.level.com.mkyong=DEBUG

#authmanager
pms.cert.service.token.request.issuerUrl=${mosip.api.internal.url}/v1/authmanager/authenticate/clientidsecretkey
pms.cert.service.token.request.clientId=mosip-pms-client
mosip.pmp.auth.appId=partner
mosip.pmp.auth.clientId=mosip-pms-client
mosip.pmp.auth.secretKey=${mosip.pms.client.secret}

# Pms common (Required only for compilation of PMS commons)
emailResourse.url=
resource.template.url=
timeZone=
mosip.mandatory-languages=
notifications.sent.before.days=
pms.notifications-schedule.init-delay=
pms.notifications-schedule.fixed-rate=
mosip.notification.timezone=

mosip.pms.esignet.claims-mapping-file-url=
mosip.pms.esignet.amr-acr-mapping-file-url=

partner.registration.sub-template=
partner.reg.content-template=
partner.status.sub-template=
partner.status.content-template=
partner.apikey.status.sub-template=
apikey.status.content-template=

